pipeline {
    agent any
    stages {
        stage('Checkout Code') {
            steps {
                git branch:'main', url:'https://github.com/v-suneetha/Ansible-Learning.git'
            }
        }
        stage('Build'){
            steps {
                dir('project2') {
                    echo 'Building'
                }
            }
        }
        stage('Test')
        {
            steps {
                dir('project2/myapp') {
                sh 'npm install'
                sh 'npm test'
                }
            }
        }
        
        stage('Deploy')
        {
            steps{
                dir('project2/myapp') {
                sh 'ansible-playbook -i inventory.ini deploy.yaml -u ubuntu'
                }
            }
        }
        
    }
}

